sudo: false
language: node_js

node_js:
  - '10'

branches:
  only:
    - master

cache:
  directories:
    - node_modules

before_install:
  - npm update

install:
  - npm ci

script:
  - npm test
  - npm run coveralls
  - cd docs && npm install && npm run build && cd -

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GH_TOKEN
    keep-history: true
    local-dir: docs/public
    target-branch: gh-pages
    repo: sanusart/react-dropdown-select
    on:
      branch: master
